# Use a imagem base do PostgreSQL
FROM postgres:latest

# Defina as variáveis de ambiente para a configuração do banco de dados
ENV POSTGRES_DB test
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD 01111971

# Exponha a porta do banco de dados (5432 é a porta padrão do PostgreSQL)
EXPOSE 5432
